### ISSUE TITLE
Apply "Private Data" for GDPR compliance

### ISSUE THREAD

**Issue by agamvrinos** [hyperdebt/blockchain#5]

**Comment by Yzoni** [comment]
So what does this mean exactly? Some thoughts:

First, private data in the sense that each municipality has their own private database of their citizens and the blockchain ledger only stores a hash of the key matching the public state. For the CJIB to access it we need one server not owned by the CJIB that is able access all data to provide the restapi, now who is going to run this. To me this solution almost looks like our Corda solution because how is the data decentralized now...

Secondly, what I think was proposed during the CJIB meeting, do private data in the sense that the blockchain still only stores hashes, but the full database is distributed among municipalities using some additional database protocol besides what hyperledger provides. Seems unfeasible given the time. 

Zeki only ever talked about that we cannot store BSN in plain on the blockchain. So how is CJIB ever going to query a specific person?

**Comment by Yzoni** [comment]
Little research on the BSN:

We just cannot store BSN, because of GDPR: https://autoriteitpersoonsgegevens.nl/nl/onderwerpen/identificatie/burgerservicenummer-bsn

We can still store the other data, so CJIB has to query based on other characteristics like name, birth date, address. And hopefully this delivers a unique match.

**Comment by HvanVeltom** [comment]
Here is how I interpreted the proposal of the CJIB meeting. Each municipality stores only the hash of the data and an api endpoint. All actual data is stored locally by municipality and the API endpoint is used to access this locally stored data. This article describes this solution as well:  https://medium.com/wearetheledger/the-blockchain-gdpr-paradox-fc51e663d047
which is more inline with your first suggestion.

**Comment by Yzoni** [comment]
Ah yes nice Harvey. Oke so then third option is maybe to still use the private data function of Fabric such that data is kept of chain, but give each municipality full read access to all records?

To refer back to a link Aggelos gave about GDPR compliance: https://stackoverflow.com/questions/49773547/how-to-implement-distibuted-db-on-hyperledger-fabric-gdpr With the newer hyperledger a separate state database is not really necessary anymore, so the second option given above is kind a unnecessary.
